# src/conda.yml
name: adult-train-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.8.0
      - mlflow-skinny==2.8.0
      - scikit-learn
      - pandas
      - azureml-mlflow
      - azureml-core
